Enable Login/Signup Funtion
2024-CMPU9010-GROUP-3/PROJECT pull request #204
Opened 2024-10-17 21:56 UTC by YuanshuoDu

### Description

This pull request enables the login and signup functionality within the application. The implementation includes user authentication features that allow users to create accounts and log in securely. The motivation behind this change is to provide a seamless user experience for account management, ensuring that users can easily register and access their accounts. This feature is essential for applications that require user-specific data and personalized experiences.

Fixes # (issue)

### Type of change

Please select the option that best describes the changes made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

### Changes

1. User Registration (Signup)

- Implemented a user registration form that collects first name, last name, email, and password.
- Added validation for required fields and password complexity requirements.
- Included functionality to store user information and authentication token in local storage upon successful registration.
- Implemented error handling to provide feedback for registration failures.

2. User Login

- Developed a login form that allows users to log in using their email or username and password.
- Added validation to ensure fields are not empty before submission.
- Implemented functionality to retrieve and store the authentication token upon successful login.
- Included error handling to display appropriate messages for login failures.

3. Password Visibility Toggle

- Added a feature to toggle the visibility of password fields in both the signup and login forms, enhancing user experience by reducing input errors.

4. Routing and Redirection

- Implemented redirection logic to navigate users to the home page after successful login or signup.
- Added checks to prevent logged-in users from accessing the login or signup pages.

2024-10-17 22:22 UTC, 1Solon requested changes

2024-10-17 22:22 UTC, 1Solon commented on Backend/go.sum
Why did you edit this?

2024-10-17 22:22 UTC, 1Solon commented on Backend/go.mod
It would help if you informed @ankraus before you start adjusting `go.mod` this could cause failures.

2024-10-17 22:22 UTC, 1Solon commented on Backend/cmd/main/main.go
Assuming this was debug, please remove this before you merge.

2024-10-17 22:30 UTC, ankraus requested changes
Please remove the changes you made to any backend files

2024-10-18 16:36 UTC, ankraus approved these changes

2024-10-18 16:38 UTC, ankraus commented
PR is fine from my side. @KaustubhTrivedi please review the changes in the frontend

2024-10-18 16:57 UTC, 1Solon approved these changes

2024-10-18 19:24 UTC, merged